#!/usr/bin/guile \
-e main -s

 a nice helper to (hopefully) ease the pain associated with configuring einit
!#

(define (help)
        (display "please tell me what to do!")
        (newline))

(define ipc-commands (list))
(define is-sandbox #f)
(define is-version-request #f)
(define is-licence-request #f)

(define (main args)
        (map (lambda (arg)
                     (cond
                        ((or (string=? arg "-v")
                             (string=? arg "--version")) (set! is-version-request #t))
                        ((or (string=? arg "-L")
                             (string=? arg "--licence")) (set! is-licence-request #t))
                        ((string=? arg "--wtf") (set! ipc-commands (append (list "examine configuration") ipc-commands)))
                        ((string=? arg "--sandbox") (set! is-sandbox #t))
                        (else #f)))
             (cdr args))

        (cond
          (is-licence-request (system (string-append (dirname (car args)) "/einit-core -L")))
          (is-version-request (system (string-append (dirname (car args)) "/einit-core -v")))
          ((> (length ipc-commands) 0)
            (system (string-append 
                      (dirname (car args))
                      "/einit-core"
                      (if is-sandbox " --sandbox" "")
                      (letrec ((collect (lambda (lis str)
                                               (if (null? lis) str
                                                   (string-append " --ipc \"" (car lis) "\"" (collect (cdr lis) str))))))
                        (collect ipc-commands "")))))
          (else
            (help))))
