#!/bin/sh

echo '<?xml version="1.0"?>
<xsl:stylesheet version = "1.0"
        xmlns:xsl = "http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text"/>
<xsl:template match="module">"<xsl:value-of select="@name"/>", "<xsl:value-of select="@id"/>", "<xsl:value-of select="@provides"/>", "<xsl:value-of select="@requires"/>", "<xsl:value-of select="@before"/>", "<xsl:value-of select="@after"/>", "<xsl:value-of select="@shutdown-before"/>", "<xsl:value-of select="@shutdown-after"/>", "<xsl:value-of select="@functions"/>"</xsl:template>
</xsl:stylesheet>
'>/tmp/einit-modules-to-csv.xslt

/sbin/einit --ipc-command "list modules --xml">/tmp/einit-modules.xml

echo '"Module Name", "ID", "Provides", "Requires", "Before", "After", "Before (Shutdown)", "After (Shutdown"), "Functions"' > einit-modules.csv
Xalan /tmp/einit-modules.xml /tmp/einit-modules-to-csv.xslt >> einit-modules.csv
