#!/bin/sh

ACTION="$1"

if grep -q einit /proc/1/cmdline
then
    EXEC="/sbin/einit-control"
    EINIT="yes"
else
    EXEC="/etc/init.d/ipw3945d"
    EINIT="no"
fi

case "${ACTION}" in
    start)
	if [ "${EINIT}" = "yes" ]
	then
	    ARGS="rc ipw3945d enable"
	else
	    ARGS="--quiet start"
	fi
	;;
    stop)
	if [ "${EINIT}" = "yes" ]
	then
	    ARGS="rc ipw3945d disable"
	else
	    ARGS="--quiet stop"
	fi
	;;
    *)
	echo "$0: wrong arguments" >&2
	echo "Call with <interface> <start|stop>" >&2
	exit 1
	;;
esac

export IN_BACKGROUND=true

if [ -x "${EXEC}" ]
then
    ${EXEC} ${ARGS}
    exit 0
else
    logger -t ipw3945d "Error: Couldn't start, no ${EXEC} !"
    exit 1
fi

# vim: set ts=4
