#!/bin/sh

db_name="einit"
table_name_modules="einitModules"

echo '<?xml version="1.0"?>
<xsl:stylesheet version = "1.0"
        xmlns:xsl = "http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text"/>
<xsl:template match="module">
INSERT INTO `'${db_name}'`.`'${table_name_modules}'` (`name`, `rid`, `provides`, `requires`, `before`, `after`, `shutdownBefore`, `shutdownAfter`, `functions`)
 VALUES
 ("<xsl:value-of select="@name"/>",
  "<xsl:value-of select="@id"/>",
  "<xsl:value-of select="@provides"/>",
  "<xsl:value-of select="@requires"/>",
  "<xsl:value-of select="@before"/>",
  "<xsl:value-of select="@after"/>",
  "<xsl:value-of select="@shutdown-before"/>",
  "<xsl:value-of select="@shutdown-after"/>",
  "<xsl:value-of select="@functions"/>")
 ON DUPLICATE KEY UPDATE
  `name`="<xsl:value-of select="@name"/>",
  `provides`="<xsl:value-of select="@provides"/>",
  `requires`="<xsl:value-of select="@requires"/>",
  `before`="<xsl:value-of select="@before"/>",
  `after`="<xsl:value-of select="@after"/>",
  `shutdownBefore`="<xsl:value-of select="@shutdown-before"/>",
  `shutdownAfter`="<xsl:value-of select="@shutdown-after"/>",
  `functions`="<xsl:value-of select="@functions"/>";
</xsl:template>
</xsl:stylesheet>
'>/tmp/einit-modules-to-sql.xslt

/sbin/einit --ipc-command "list modules --xml">/tmp/einit-modules.xml

echo 'CREATE TABLE IF NOT EXISTS `'${table_name_modules}'` (
  `rid` varchar(255) NOT NULL default "",
  `name` varchar(255) NOT NULL default "",
  `provides` text,
  `requires` text,
  `after` text,
  `before` text,
  `shutdownAfter` text,
  `shutdownBefore` text,
  `functions` text,
  PRIMARY KEY  (`rid`)
);' > einit-modules.sql

Xalan /tmp/einit-modules.xml /tmp/einit-modules-to-sql.xslt >> einit-modules.sql
