#!/bin/sh
# -----------------
# einit data install script
# -----------------
# argument 1 is the path to install to, argument 2 is the libdirname
# example:
#  ./install / lib
# -----------------
# Copyright (c) 2007, Magnus Deininger
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright notice, this list of conditions and the
#      following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and
#      the following disclaimer in the documentation and/or other materials provided with the distribution.
#    * Neither the name of the project nor the names of its contributors may be used to endorse or promote
#      products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# -----------------

if [ "$PREFIX" = "" ]; then
 echo "PREFIX=\"$1\"
ETCDIR=\"$1/etc/einit\"
ETCXDIR=\"$1/etc\"
ELIBDIR=\"$2\"
LIBDIR=\"$1/$2/einit\"
MODDIR=\"$1/$2/einit/modules\"
BINDIR=\"$1/bin\"
SBINDIR=\"$1/sbin\"
INCLUDEDIR=\"$1/include\"
BOOTSTRAPDIR=\"$1/$2/einit/bootstrap/\"

INSTALL=install
" > config.sh;
fi

cd data && ./install
