#!/bin/sh
#------------------------------------------------------------------------------
# makerelease
# einit
#
# Created on 2007-07-14
#------------------------------------------------------------------------------
# this script can be used to create release- and snapshot-tarballs for einit.
# to use, call this script from the directory containing the main einit-tree
# and pass the release/snapshot name as the first parameter
#------------------------------------------------------------------------------
# Copyright (c) 2006, Magnus Deininger
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution.
#    * Neither the name of the project nor the names of its contributors may be
#      used to endorse or promote products derived from this software without
#      specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

rm -Rf einit-modules-xml-$1 &&
cp -a modules/xml/ einit-modules-xml-$1 &&
cd einit-modules-xml-$1 &&
#make clean &&
rm -fR sandbox* einit.* web build docs &&
rm -fR `find . -name "nohup.out" -o -name "CVS*" -o -name ".svn" -o -name "*~" -o -iname "" -o -name "*.mk" -o -name "*.so" -o -name "*.o" -o -iname ".[a-z#]*" -o -name "1" -o -iname "*do_sandbox*" -o -name "config.mk" -o -name "config.sh"` &&

cd .. &&
tar -cjf einit-modules-xml-$1.tar.bz2 einit-modules-xml-$1 &&
tar -czf einit-modules-xml-$1.tar.gz einit-modules-xml-$1 &&

su -c "cp einit-modules-xml-$1.tar.bz2 /usr/portage/distfiles" &&

cp distro/gentoo/portdir_overlay/sys-apps/einit-modules-xml/einit-modules-xml-0.60.0.ebuild distro/gentoo/portdir_overlay/sys-apps/einit-modules-xml/einit-modules-xml-$1.ebuild &&
svn add distro/gentoo/portdir_overlay/sys-apps/einit-modules-xml/einit-modules-xml-$1.ebuild &&

ebuild distro/gentoo/portdir_overlay/sys-apps/einit-modules-xml/einit-modules-xml-$1.ebuild manifest
#cd einit-$1/gentoo/portage &&

#tar -cjf ../../../einit-$1-portage-overlay.tar.bz2 . &&
#cd ../../../ &&
