#!/bin/sh

libdir=$1

if [ -z "$libdir" ]; then libdir="lib"; fi

mkdir /tmp/initramfs
cd /tmp/initramfs

mkdir -p ${libdir}/einit/bootstrap
mkdir -p ${libdir}/einit/modules
mkdir -p ${libdir}/einit/bin
mkdir -p ${libdir}

cp /${libdir}/einit/bin/einit-core ${libdir}/einit/bin
cp /${libdir}/einit/bootstrap/* ${libdir}/einit/bootstrap
cp /${libdir}/einit/modules/*initramfs* ${libdir}/einit/modules
cp /${libdir}/einit/einit.xml ${libdir}/einit

cp /${libdir}/*pthread* ${libdir}/
cp /${libdir}/libdl* ${libdir}/
cp /${libdir}/ld-* ${libdir}/
cp /${libdir}/libc[-.]* ${libdir}/

if [ "$libdir" != "lib" ]; then ln -sf "$libdir" lib; fi

cp /sbin/einit ./init

mkdir ./dev
cd dev
mknod -m 660 console c 5 1
mknod -m 666 null c 1 3
mknod -m 600 tty1 c 4 1
cd ..

rm /boot/einit-initramfs
find . | cpio -o -H newc | gzip > /boot/einit-initramfs

cd

rm -Rf /tmp/initramfs
