include ../config.mk

all:

install: all
	${INSTALL} ${IPARAM} -d ${DESTDIR}/${USHAREDIR}
	${INSTALL} ${IPARAM} -d ${DESTDIR}/${USHAREDIR}/images
	${INSTALL} ${IPARAM} -m 0644 einit.png ${DESTDIR}/${USHAREDIR}/images
